In [1]:
import torch

d:\ProgramData\Anaconda3\envs\torch\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
torch.__version__

'1.10.2'

In [3]:
x= torch.empty(4,2)
print(x)

tensor([[8.1275e-44, 7.1466e-44],
        [7.8473e-44, 6.4460e-44],
        [6.7262e-44, 7.4269e-44],
        [6.7262e-44, 1.2612e-43]])


In [4]:
x=torch.rand(4,2)
print(x)

tensor([[0.4505, 0.1084],
        [0.8682, 0.1542],
        [0.9582, 0.7816],
        [0.2709, 0.8672]])


In [5]:
x = torch.zeros(4,2,dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [6]:
x = torch.tensor([3,2.3])
print(x)

tensor([3.0000, 2.3000])


In [7]:
x = x.new_ones(2,4,dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [8]:
x = torch.randn_like(x,dtype = torch.float)
print(x)

tensor([[ 0.0010,  0.7195,  0.0824, -0.7688],
        [-0.2613,  0.2634, -0.5144,  0.8208]])


In [9]:
print(x.size())

torch.Size([2, 4])


In [10]:
y = torch.rand(2,4)

In [11]:
x
y

tensor([[0.5197, 0.8584, 0.9690, 0.3888],
        [0.3834, 0.0391, 0.1270, 0.9724]])

In [12]:
x+y

tensor([[ 0.5208,  1.5780,  1.0514, -0.3800],
        [ 0.1221,  0.3025, -0.3874,  1.7931]])

In [13]:
x

tensor([[ 0.0010,  0.7195,  0.0824, -0.7688],
        [-0.2613,  0.2634, -0.5144,  0.8208]])

In [14]:
print(torch.add(x,y))

tensor([[ 0.5208,  1.5780,  1.0514, -0.3800],
        [ 0.1221,  0.3025, -0.3874,  1.7931]])


In [17]:
x = torch.randn(4,5)
x.view(4,-1)

tensor([[ 0.0144, -0.2724,  2.1625,  0.3486,  0.5762],
        [-0.8836,  1.0205, -1.2431, -0.6620, -0.8288],
        [ 0.0596,  0.8373,  0.4222, -1.4724, -0.4945],
        [-0.3299,  1.3361,  0.3009, -1.2013, -0.9233]])

In [18]:
x.item()

ValueError: only one element tensors can be converted to Python scalars

In [21]:
torch.cuda.is_available()

False