In [11]:
import torch

In [12]:
torch.cuda.is_available()
print(torch.__version__)

1.10.2


In [13]:
for i in range(4):
    print(torch.rand((1,2)))

tensor([[0.1368, 0.6310]])
tensor([[0.7691, 0.8971]])
tensor([[0.9179, 0.8538]])
tensor([[0.1499, 0.3567]])


In [15]:
import torch.nn as nn
import torch

In [21]:
def identify_func(x):
    return x

In [16]:
x = torch.Tensor([[0,1]])
W1= torch.rand((2,2))
b1 = torch.rand((1,2))
z1 = torch.mm(x,W1.t())+b1
a1 = torch.sigmoid(z1)


In [17]:
print(z1)
print(a1)

tensor([[0.8064, 0.7937]])
tensor([[0.6913, 0.6886]])


In [18]:
torch.mm(a1,a1.t())

tensor([[0.9521]])

In [19]:
linear_ih = nn.Linear(in_features=2, out_features=2)
linear_ho = nn.Linear(in_features=2, out_features=1)
activation_layer = nn.Sigmoid()

In [25]:
z1 = linear_ih(x)
a1 = activation_layer(z1)
z2 = linear_ho(a1)
y = activation_layer(z2)
print(y.item())

0.5897313356399536


In [26]:
print(x)
print(z1)
print(a1)
print(z2)
print(y)

tensor([[0., 1.]])
tensor([[0.6206, 0.1391]], grad_fn=<AddmmBackward0>)
tensor([[0.6504, 0.5347]], grad_fn=<SigmoidBackward0>)
tensor([[0.3629]], grad_fn=<AddmmBackward0>)
tensor([[0.5897]], grad_fn=<SigmoidBackward0>)


In [28]:
class Network(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(Network, self).__init__()
        self.linear_ih = nn.Linear(in_features=input_size, out_features=hidden_size)
        self.linear_ho = nn.Linear(in_features=hidden_size, out_features=output_size)
        self.activation_layer = nn.Sigmoid()
    
    def identity_func(self, x):
        return x
    
    def forward(self,x):
        z1 = self.linear_ih(x)
        a1 = self.activation_layer(z1)
        z2 = self.linear_ho(a1)
        y = self.activation_layer(z2)
        return y
    

In [ ]:
net = Network(input_size)