In [1]:
import torch

d:\ProgramData\Anaconda3\envs\torch\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
torch.cuda.is_available()
print(torch.__version__)

1.10.2


In [3]:
for i in range(4):
    print(torch.rand((1,2)))

tensor([[0.8104, 0.9666]])
tensor([[0.1679, 0.0868]])
tensor([[0.8695, 0.2531]])
tensor([[0.3210, 0.4819]])


In [4]:
import torch.nn as nn
import torch

In [5]:
def identify_func(x):
    return x

In [6]:
x = torch.Tensor([[0,1]])
W1= torch.rand((2,2))
b1 = torch.rand((1,2))
z1 = torch.mm(x,W1.t())+b1
a1 = torch.sigmoid(z1)


In [7]:
print(z1)
print(a1)

tensor([[1.2906, 0.2735]])
tensor([[0.7843, 0.5680]])


In [8]:
torch.mm(a1,a1.t())

tensor([[0.9376]])

In [9]:
linear_ih = nn.Linear(in_features=2, out_features=2)
linear_ho = nn.Linear(in_features=2, out_features=1)
activation_layer = nn.Sigmoid()

In [10]:
z1 = linear_ih(x)
a1 = activation_layer(z1)
z2 = linear_ho(a1)
y = activation_layer(z2)
print(y.item())

0.5992491245269775


In [11]:
print(x)
print(z1)
print(a1)
print(z2)
print(y)

tensor([[0., 1.]])
tensor([[-0.5344,  0.9325]], grad_fn=<AddmmBackward0>)
tensor([[0.3695, 0.7176]], grad_fn=<SigmoidBackward0>)
tensor([[0.4023]], grad_fn=<AddmmBackward0>)
tensor([[0.5992]], grad_fn=<SigmoidBackward0>)


In [12]:
class Network(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super().__init__()
        self.linear_ih = nn.Linear(in_features=input_size, out_features=hidden_size)
        self.linear_ho = nn.Linear(in_features=hidden_size, out_features=output_size)
        self.activation_layer = nn.Sigmoid()
    
    def identity_func(self, x):
        return x
    
    def forward(self,x):
        z1 = self.linear_ih(x)
        a1 = self.activation_layer(z1)
        z2 = self.linear_ho(a1)
        y = self.activation_layer(z2)
        return y
    

In [13]:
net = Network(input_size=2,hidden_size=2,output_size=1)
y = net(x)
print(y)

tensor([[0.4700]], grad_fn=<SigmoidBackward0>)


In [14]:
P = torch.Tensor([0.4,0.6])
Q = torch.Tensor([0.0,1.0])

In [15]:
def self_information(x):
    print(x)
    print(torch.log(x))
    return -torch.log(x)
def entropy(x):
    e = 1e-30
    return torch.sum((x+e)*self_information(x+e))

In [16]:
print(entropy(P))

tensor([0.4000, 0.6000])
tensor([-0.9163, -0.5108])
tensor(0.6730)


In [75]:
class Network(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super().__init__()
        self.linear_ih = nn.Linear(in_features=input_size, out_features=hidden_size)
        self.linear_ho = nn.Linear(in_features=hidden_size, out_features=output_size)
        self.activation_layer = nn.Sigmoid()
    def forward(self,x):
        z1 = self.linear_ih(x)
        a1 = self.activation_layer(z1)
        z2 = self.linear_ho(a1)
        y = self.activation_layer(z2)
        return y
    

In [76]:
class Net(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(Network).__init__()
        self.flatten = lambda x: x.view(x.size(0), -1)
    def forward(self,x):
        x=self.flatten(x)
        return x

In [108]:
def train(model, train_loader, loss_func, optimizer, step, device, print_step = 200):
    model.train()
    for batch_idx, (data,target) in enumerate(train_loader):
        pass
        

In [109]:
import matplotlib.pyplot as plt
from PIL import Image

In [111]:
img = Image.open('cat.jpeg')

In [112]:
print(type(img))

<class 'PIL.JpegImagePlugin.JpegImageFile'>


In [116]:
grey_cat = img.convert("L")

In [124]:
grey_cat.size

(1129, 750)